steal
.plugins('steal/generate','steal/get','steal/build','steal/coffee','steal/less','steal/clean')

.plugin('funcunit').
then('pages/init').plugins('jquery',
'jquery/controller',
'jquery/view','jquery/view/ejs'
,'jquery/view/jaml'
,'jquery/view/micro',
'jquery/model',
'jquery/event/default',
'jquery/event/destroyed',
'jquery/event/drag','jquery/event/drag/limit','jquery/event/drag/scroll',
'jquery/event/drop',
'jquery/event/hover',
'jquery/event/resize',
'jquery/dom/compare',
'jquery/dom/closest',
'jquery/dom/within',
'jquery/dom/form_params',
'jquery/dom/dimensions',
'jquery/dom/fixture',
'jquery/dom/cookie',
'documentjs'
)
